### ISSUE TITLE
infografia Hilos C#

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/infografia-de-hilos-Arnold-Js#2]
[infografia de hilos en C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Arnold-Js/files/6468374/infografia.de.hilos.en.C.pdf)

**Comment by bg55-a** [comment]
Calificación: 20
Califico:  Adolfo Germán Vasquez Rojas

**Comment by josealfredo79** [comment]
Esta bien hecho y  revisado.
