### ISSUE TITLE
Infografia de Hilos C# 

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/infografia-de-hilos-Arnold-Js#2]
[Hilos Info.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Arnold-Js/files/8394343/Hilos.Info.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
